[config.wallpaper]
command = "awww img {{ image }} --transition-type center --transition-fps 60 --transition-duration 1.5"
set = true

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.dotfiles/.config/hypr/conf/colors.conf"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/.dotfiles/.config/kitty/colors.conf"

[templates.rofi]
input_path = "./templates/rofi-colors.rasi"
output_path = "~/.dotfiles/.config/rofi/colors.rasi"

[templates.waybar]
input_path = "./templates/colors.css"
output_path = "~/.dotfiles/.config/waybar/colors.css"

[templates.gtk3]
input_path = "./templates/gtk-colors.css"
output_path = "~/.dotfiles/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "./templates/gtk-colors.css"
output_path = "~/.dotfiles/.config/gtk-4.0/colors.css"

[templates.dunst]
input_path = "./templates/dunstrc-colors"
output_path = "~/.dotfiles/.config/dunst/dunstrc"

[templates.qt6ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.dotfiles/.config/qt6ct/colors/matugen.conf"

[templates.qt5ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.dotfiles/.config/qt5ct/colors/matugen.conf"

[templates.btop]
input_path = "./templates/btop.theme"
output_path = "~/.dotfiles/.config/btop/themes/matugen.theme"

[templates.papirus-folders]
input_path = './templates/papirus-folders-colors.toml'
output_path = '~/.cache/papirus-folders-colors.toml'
colors_to_compare = [
    { name = "adwaita", color = "#93c0ea" },
    { name = "blue", color = "#5294e2" },
    { name = "blue", color = "#004c6b"},
    { name = "breeze", color = "#57b8ec" },
    { name = "breeze", color = "#88d1ec" },
    { name = "carmine", color = "#a30002" },
    { name = "darkcyan", color = "#45abb7" },
    { name = "green", color = "#a1bf80" },
    { name = "indigo", color = "#838dca" },
    { name = "nordic", color = "#9db4cb" },
    { name = "palebrown", color = "#d6c9bd" },
    { name = "palebrown", color = "#ffb59b" },
    { name = "pink", color = "#ec87a9" },
    { name = "pink", color = "#6c3353" },
    { name = "teal", color = "#159a80" },
    { name = "white", color = "#e4e4e4" },
    { name = "yellow", color = "#f3c863" },
    { name = "yellow", color = "#4b4900" },
    { name = "black", color = "#797979" },
    { name = "bluegray", color = "#869aa4" },
    { name = "brown", color = "#bda68e" },
    { name = "cyan", color = "#41c7d8" },
    { name = "deeporange", color = "#e98a68" },
    { name = "grey", color = "#a6a6a6" },
    { name = "magenta", color = "#d192e0" },
    { name = "orange", color = "#eba96a" },
    { name = "paleorange", color = "#ebd1a7" },
    { name = "red", color = "#e27c7c" },
    { name = "red", color = "#ffb4ab" },
    { name = "violet", color = "#9b7fcb" },
    { name = "violet", color = "#553b71" }
]
compare_to = "{{ colors.primary.default.hex }}"
post_hook = "SUDO_ASKPASS=~/.dotfiles/.local/bin/askPassword.sh sudo -A true && notify-send -i 'dialog-information-symbolic' 'Updating folders' 'Applying folder color scheme...' -r 8 -t 8000 && papirus-folders -C {{ closest_color }} --theme Papirus-Dark"
