source = ./conf/autostart.conf
source = ./conf/keybinds.conf
source = ./conf/monitors.conf
source = ./conf/rules.conf
source = ./conf/environments.conf
source = ./conf/input.conf
source = ./conf/animations.conf
source = ./conf/decoration.conf
source = ./conf/general.conf
source = ./conf/misc.conf
# source = ./conf/nvidia.conf
