animations {
    enabled = true

    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    animation = windows, 1, 2, md3_decel, popin 80%
    animation = border, 1, 2, default
    animation = fade, 1, 1.5, md3_decel
    animation = workspaces, 1, 2, easeOutExpo, slide
    animation = specialWorkspace, 1, 2, md3_decel, slidevert
}
