animations {
    enabled = true

    bezier = fastSpatial, 0.27, 1.06, 0.18, 1.00 # use 3.5
    bezier = fastEffect, 0.31, 0.94, 0.34, 1.00 # use 1.5

    animation = windows, 1, 3.5, fastSpatial, slide
    animation = border, 1, 1.5, fastEffect
    animation = fade, 1, 1.5, fastEffect
    animation = workspaces, 1, 3.5, fastSpatial, slide
    animation = monitorAdded, 1, 1.5, fastEffect

    animation = layersIn, 1, 1.5, fastEffect, slide
    animation = layersOut,  1, 1.5, fastEffect, slide
}
