# Required programs
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = awww-daemon
exec-once = wl-paste --watch cliphist store
exec-once = waybar
exec-once = hypridle
exec-once = dunst
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = batteryChecker.sh
exec-once = layoutNotify.sh

# Other programs
exec-once = seafile-applet
exec-once = triliumnext
exec-once = [workspace 5 silent] sleep 2 && happ
