# Settings
source = monitors.conf
env = settingsMainMonitor,$mainMonitor
env = settingsSecondMonitor,$secondMonitor

env = settingsKeyboardName,squalius-cephalus-silakka54

env = settingsTheme,adw-gtk3-dark
env = settingsMode,dark
env = settingsIcons,Papirus-Dark
env = settingsFont,CodeNewRoman Nerd font Propo 12
env = settingsCursor,Bibata-Modern-Classic

# XDG Desktop portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb

# GDK
env = GDK_SCALE,1

# GTK Theme
env = GTK_THEME,adw-gtk3-dark

# Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# SDL
env = SDL_VIDEODRIVER,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

