# Settings
env = main_monitor,HDMI-A-1
env = second_monitor,DP-1

env = keyboard,squalius-cephalus-silakka54

env = theme,adw-gtk3
env = mode,dark
env = icons,Papirus
env = font,CodeNewRoman Nerd font Mono 12
env = cursor,Bibata-Modern-Classic

# XDG Desktop portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb

# GDK
env = GDK_SCALE,1

# GTK Theme
env = GTK_THEME,adw-gtk3-$mode

# Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# SDL
env = SDL_VIDEODRIVER,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

