#                                      __
#    ____ ____  ____  ___  _________ _/ /
#   / __ `/ _ \/ __ \/ _ \/ ___/ __ `/ / 
#  / /_/ /  __/ / / /  __/ /  / /_/ / /  
#  \__, /\___/_/ /_/\___/_/   \__,_/_/   
# /____/                                 

source = colors.conf

general {
    gaps_in = 3
    gaps_out = 6

    border_size = 2

    col.active_border = $primary
    col.inactive_border = $background

    resize_on_border = false
    allow_tearing = true

    layout = master
}
