input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle

    follow_mouse = 1

    sensitivity = 0.25

    touchpad {
        disable_while_typing = true
        natural_scroll = true
        scroll_factor = 0.6
    }
}

device {
    name = compx-vgn-f1
    accel_profile = flat
    sensitivity = 0
}

cursor {
    no_hardware_cursors = true
}
