$mainMonitor = HDMI-A-1
$secondMonitor = DP-1

monitor=$mainMonitor,1920x1080@75,0x0,1
monitor=$secondMonitor,1920x1080@60,1920x0,1

workspace=1,monitor:$mainMonitor
workspace=2,monitor:$mainMonitor
workspace=3,monitor:$mainMonitor
workspace=4,monitor:$mainMonitor
workspace=5,monitor:$mainMonitor

workspace=6,monitor:$secondMonitor
workspace=7,monitor:$secondMonitor
workspace=8,monitor:$secondMonitor
workspace=9,monitor:$secondMonitor
workspace=10,monitor:$secondMonitor
