monitor=$main_monitor,1920x1080@75,0x0,1
monitor=$second_monitor,1920x1080@60,1920x0,1

workspace=1,monitor:$main_monitor
workspace=2,monitor:$main_monitor
workspace=3,monitor:$main_monitor
workspace=4,monitor:$main_monitor
workspace=5,monitor:$main_monitor

workspace=6,monitor:$second_monitor
