#                __         
#    _______  __/ /__  _____
#   / ___/ / / / / _ \/ ___/
#  / /  / /_/ / /  __(__  ) 
# /_/   \__,_/_/\___/____/  
                  
source = colors.conf

windowrule {
    name = XWayland
    match:xwayland = true

    border_color = $secondary
}

windowrule {
    name = blueman-manager
    match:class = blueman-manager

    float = true
    size = 800 600
    center = true
    pin = true
}

windowrule {
    name = pavucontrol
    match:class = org.pulseaudio.pavucontrol

    float = true
    size = 800 600
    center = true
    pin = true
}

windowrule {
    name = Picture-in-Picture
    match:title = ^(Picture-in-Picture)$

    float = true
    size = 640 480
    move = (monitor_w*0.66) (monitor_h*0.05)
    pin = true
}

windowrule {
    name = nmtui
    match:class = network

    float = true
    center = true
    size = 1280 720
}

windowrule {
    name = systemUpdate.sh
    match:class = systemUpdate

    float = true
    center = true
    size = 1280 720
}

windowrule {
    name = btop
    match:class = btop

    float = true
    center = true
    size = 1280 720
}

windowrule {
    name = xdg-desktop-portal-gtk
    match:class = xdg-desktop-portal-gtk

    float = true
    center = true
    size = 1280 720
}

windowrule {
    name = Games by class
    match:class = ^(.*osu.*|steam_app_.*)$

    immediate = true
    monitor = HDMI-A-1
}

windowrule {
    name = Games by title
    match:title = ^(Euro Truck Simulator 2)$

    immediate = true
    monitor = HDMI-A-1
}

layerrule {
    name = Waybar
    match:namespace = waybar

    blur = true
    ignore_alpha = 0.5
}

layerrule {
    name = Rofi
    match:namespace = rofi

    blur = true
    ignore_alpha = 0.5
}

layerrule {
    name = Notifications
    match:namespace = notifications

    blur = true
    ignore_alpha = 0.5
}

# smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]
