source = monitors.conf

windowrule {
    name = utils
    match:class = ^(blueman-manager|org\.pulseaudio\.pavucontrol|network|systemUpdate|btop)$

    float = true
    size = 1280 720
    center = true
}

windowrule {
    name = pictureInPicture
    match:title = ^(Picture-in-Picture)$

    float = true
    size = 640 480
    move = (monitor_w*0.66) (monitor_h*0.05)
    pin = true
}

windowrule {
    name = portalDialogs
    match:class = ^(org\.freedesktop\.impl\.portal\.desktop\.(hyprland|gtk)|[Xx]dg-desktop-portal-gtk|hyprland-share-picker)$

    float = true
    center = true
}

windowrule {
    name = dialogs
    match:title = ^(Choose Files|Save As|Confirm to replace files|File Operation Progress|Open|Authentication Required|Add Folder to Workspace|File Upload.*|.*dialog.*|Empty Trash|Rename.*|Save.*|Extract)$

    float = true
    center = true
}

layerrule {
    name = blurRules
    match:namespace = ^(waybar|rofi|notifications)$

    blur = true
    blur_popups = true
    ignore_alpha = 0.5
}

windowrule {
    name = pinnedSatty
    match:class = com.gabm.satty

    float = true
    center = true
    pin = true
    size = 1600 900
}

windowrule {
    name = ayugramMediaViewer
    match:class = com.ayugram.desktop
    match:title = ^(Media viewer)$

    float = true
    center = true
    size = 1600 900
    monitor = $mainMonitor
}

windowrule {
    name = gamesByClass
    match:class = ^(.*osu.*|steam_app_.*|steam)$

    immediate = true
    monitor = $mainMonitor
}

windowrule {
    name = gamesByTitle
    match:title = ^(Euro Truck Simulator 2)$

    immediate = true
    monitor = $mainMonitor
}
