[display]
horizontal_padding = 0
vertical_padding = 1
width = 0
show_translation = "english"
translation_color = "dim"
font_size = "small"
bold = false
border = false
rounded_border = true
source = true
modes = ["proverb", "anime", "haiku"]
seed = 0
centered = true
