[general]
fullscreen = false
resize = { mode = "smart" }
floating-hack = true
early-exit = true
early-exit-save-as = true
corner-roundness = 12
initial-tool = "crop"
copy-command = "wl-copy"
annotation-size-factor = 2
output-filename = "~/Pictures/Screenshots/%Y-%m-%d_%H:%M:%S.png"
save-after-copy = false
default-hide-toolbars = false
focus-toggles-toolbars = false
default-fill-shapes = false
primary-highlighter = "block"
disable-notifications = false
actions-on-right-click = []
actions-on-enter = ["save-to-file"]
actions-on-escape = ["save-to-clipboard"]
right-click-copy = false
no-window-decoration = true
brush-smooth-history-size = 10
pan-step-size = 50.0
zoom-factor = 1.1
text-move-length = 50.0 
input-scale = 2.0

[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "i"
arrow = "z"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "g"

[font]
family = "Roboto"
style = "Regular"
fallback = [
    "Noto Sans CJK JP",
    "Noto Sans CJK SC",
    "Noto Sans CJK TC",
    "Noto Sans CJK KR",
    "Noto Serif CJK JP",
    "Noto Serif JP",
    "IPAGothic",
    "IPAexGothic",
    "Source Han Sans"
]
